#!/usr/bin/env sh
# Create .env with a fresh session secret and a scrypt password hash.
#
#   ./generate-secrets.sh              # random password, printed once
#   ./generate-secrets.sh 'my-password'
#
# This exists so the repository ships no default credentials. A committed
# default secret is the single most common way a demo turns into an incident:
# it works, nobody changes it, and it is already public.

set -eu

cd "$(dirname "$0")"

if [ -f .env ]; then
  echo "refusing to overwrite an existing .env - delete it first" >&2
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "node is required to generate the password hash" >&2
  exit 1
fi

PASSWORD="${1:-$(node -e "console.log(require('crypto').randomBytes(12).toString('base64url'))")}"

SESSION_SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
PASSWORD_HASH="$(node api/scripts/hash-password.js "$PASSWORD")"

umask 077   # .env is created readable only by you
cat > .env <<EOF
# Generated by generate-secrets.sh - do not commit.
SESSION_SECRET=$SESSION_SECRET
DEMO_USER=demo
DEMO_PASSWORD_HASH=$PASSWORD_HASH
COOKIE_SECURE=false
SESSION_TTL_SECONDS=3600
EOF

echo "wrote .env"
echo
echo "  username: demo"
echo "  password: $PASSWORD"
echo
echo "The password is not stored anywhere but this message - only its scrypt"
echo "hash goes into .env. Save it now."
